repos:
  # Black formatter
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  # Ruff (linter + autofix)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: ["--fix"]

  # Mypy (type checker)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        additional_dependencies:
          - types-setuptools
          - types-requests
          - types-urllib3

  # Bandit (security linter)
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: ["-r", "hexhttp"]
