#!/usr/bin/python

cfp_payloads = [
    {"Accept-Encoding":"identity"},
    {"Accept-Encoding":""},
    {"Accept-Encoding":"*;q=0"},
    {"Accept-Encoding":"gzip;q=0, br;q=0, deflate;q=0, *;q=0"},
    {"Accept-Encoding":"x-gzip"},
    {"Accept-Encoding":"compress"},
    {"Accept-Encoding":"x-compress"},
    {"Accept-Encoding":"pack200-gzip"},
    {"Accept-Encoding":"bzip2"},
    {"Accept-Encoding":"lzma"},
    {"Accept-Encoding":"xz"},
    {"Accept-Encoding":"zstd;q=0"},
    {"Accept-Encoding":"sdch"},
    {"Accept-Encoding":"peerdist"},
    {"Accept-Encoding":"aes128gcm"},
    {"Transfer-Encoding":"identity"},
    {"Transfer-Encoding":"compress"},
    {"Transfer-Encoding":"x-gzip"},
    {"Transfer-Encoding":""},
    {"Accept":"text/event-stream"},
    {"Accept":"text/x-component"},
    {"Accept":"text/vnd.turbo-stream.html"},
    {"Accept":"text/x-handlebars-template"},
    {"Accept":"text/x-mustache"},
    {"Accept":"text/x-jade"},
    {"Accept":"text/x-pug"},
    {"Accept":"text/x-ejs"},
    {"Accept":"text/x-erb"},
    {"Accept":"text/x-dust"},
    {"Accept":"text/html-partial"},
    {"Accept":"multipart/mixed"},
    {"Accept":"multipart/alternative"},
    {"Accept":"multipart/related"},
    {"Accept":"multipart/parallel"},
    {"Accept":"multipart/digest"},
    {"Accept":"multipart/byteranges"},
    {"Accept":"multipart/form-data"},
    {"Accept":"message/http"},
    {"Accept":"message/partial"},
    {"Accept":"application/http"},
    {"Accept":"application/signed-exchange;v=b3"},
    {"Accept":"application/webbundle"},
    {"Accept":"application/wbn"},
    {"Accept":"application/amphtml"},
    {"Accept":"text/amp-html"},
    {"Accept":"font/woff"},
    {"Accept":"font/woff2"},
    {"Accept":"font/ttf"},
    {"Accept":"font/otf"},
    {"Accept":"font/sfnt"},
    {"Accept":"font/collection"},
    {"Accept":"model/gltf+json"},
    {"Accept":"model/gltf-binary"},
    {"Accept":"model/stl"},
    {"Accept":"model/obj"},
    {"Accept":"model/3mf"},
    {"Accept":"model/vrml"},
    {"Accept":"model/x3d+xml"},
    {"Accept":"application/schema+json"},
    {"Accept":"application/schema-instance+json"},
    {"Accept":"application/vnd.oai.openapi+json"},
    {"Accept":"application/vnd.oai.openapi"},
    {"Accept":"application/swagger+json"},
    {"Accept":"application/wsdl+xml"},
    {"Accept":"application/wadl+xml"},
    {"Accept":"application/raml+yaml"},
    {"Accept":"application/vnd.api-blueprint"},
    {"Accept":"application/vnd.spring-boot.actuator.v1+json"},
    {"Accept":"application/vnd.spring-boot.actuator.v2+json"},
    {"Accept":"application/vnd.spring-boot.actuator.v3+json"},
    {"Accept":"application/health+json"},
    {"Accept":"application/vnd.error+json"},
    {"Accept":"application/problem+xml"},
    {"Accept":"application/jwt"},
    {"Accept":"application/jose"},
    {"Accept":"application/jose+json"},
    {"Accept":"application/jwk+json"},
    {"Accept":"application/jwk-set+json"},
    {"Accept":"application/csp-report"},
    {"Accept":"application/reports+json"},
    {"Accept":"application/expect-ct-report+json"},
    {"Accept":"application/coap-payload"},
    {"Accept":"application/cose"},
    {"Accept":"application/cwt"},
    {"Accept":"application/dns-json"},
    {"Accept":"application/dns-message"},
    {"Accept":"application/vnd.mapbox-vector-tile"},
    {"Accept":"application/x-protobuf; type=mapbox.vector.Tile"},
    {"Accept":"application/vnd.mapbox.vector-tile"},
    {"Accept":"text/mapml"},
    {"Accept":"application/dicom"},
    {"Accept":"application/dicom+json"},
    {"Accept":"application/fhir+xml"},
    {"Accept":"application/hl7v2+er7"},
    {"Accept":"application/sarif+json"},
    {"Accept":"application/scap+xml"},
    {"Accept":"application/taxii+json"},
    {"Accept":"application/stix+json"},
    {"Accept":"application/vnd.docker.distribution.manifest.v2+json"},
    {"Accept":"application/vnd.oci.image.manifest.v1+json"},
    {"Accept":"application/vnd.oci.image.index.v1+json"},
    {"Accept":"application/vnd.docker.container.image.v1+json"},
    {"Accept":"application/prs.hal-forms+json"},
    {"Accept":"application/vnd.hyper+json"},
    {"Accept":"application/vnd.uber+json"},
    {"Accept":"application/vnd.mason+json"},
    {"Accept":"application/vnd.amundsen.maze+xml"},
    {"Accept":"application/json-home"},
    {"Accept":"text/uri-list"},
    {"Accept":"application/link-format"},
    {"Accept":"application/linkset"},
    {"Accept":"application/linkset+json"},
    {"Accept":"application/alto-directory+json"},
    {"Accept":"application/calendar+json"},
    {"Accept":"application/calendar+xml"},
    {"Accept":"application/jscalendar+json"},
    {"Accept":"application/vnd.citationstyles.style+xml"},
    {"Accept":"application/x-research-info-systems"},
    {"Accept":"text/x-bibliography"},
    {"Accept":"application/mbox"},
    {"Accept":"application/vnd.ms-outlook"},
    {"Accept":"text/enriched"},
    {"Accept":"text/richtext"},
    {"Accept":"text/sgml"},
    {"Accept":"text/tab-separated-values"},
    {"Accept":"text/dns"},
    {"Accept":"text/cql"},
    {"Accept":"text/cql-expression"},
    {"Accept":"text/cql-identifier"},
    {"Accept":"text/provenance-notation"},
    {"Accept":"text/strings"},
    {"Accept":"text/jcr-cnd"},
    {"Accept":"text/spdx"},
    {"Accept":"text/prs.lines.tag"},
    {"Accept":"text/cache-manifest"},
    {"Accept":"text/vtt"},
    {"Accept":"text/shex"},
    {"Accept":"text/shaclc"},
    {"Accept":"application/xacml+json"},
    {"Accept":"application/xacml+xml"},
    {"Accept":"application/xcap-diff+xml"},
    {"Accept":"application/xcap-el+xml"},
    {"Accept":"application/xcap-ns+xml"},
    {"Accept":"application/yang-data+json"},
    {"Accept":"application/yang-data+xml"},
    {"Accept":"application/yang-patch+json"},
    {"Accept":"application/yang-patch+xml"},
    {"Accept":"application/webpush-options+json"},
    {"Accept":"application/push-options+json"},
    {"Accept":"application/subscription+json"},
    {"Accept":"text/plain; format=flowed"},
    {"Accept":"text/plain; format=fixed"},
    {"Accept":"text/html; charset=utf-8; component=true"},
    {"Accept":"text/html; partial=true"},
    {"Accept":"text/html; fragment=true"},
    {"Accept":"text/html; ajax=true"},
    {"Accept":"text/html; layout=false"},
    {"Accept":"text/html; layout=none"},
    {"Accept":"text/html; turbo=true"},
    {"Accept":"text/html; pjax=true"},
    {"X-Format":"event-stream"},
    {"X-Format":"sse"},
    {"X-Format":"multipart"},
    {"X-Format":"protobuf"},
    {"X-Format":"msgpack"},
    {"X-Format":"cbor"},
    {"X-Format":"bson"},
    {"X-Format":"grpc"},
    {"X-Format":"thrift"},
    {"X-Format":"capnp"},
    {"X-Format":"flatbuf"},
    {"X-Format":"arrow"},
    {"X-Format":"feather"},
    {"X-Format":"hdf5"},
    {"X-Format":"raw"},
    {"X-Format":"binary"},
    {"X-Format":"html-partial"},
    {"X-Format":"fragment"},
    {"X-Format":"component"},
    {"X-Format":"turbo-stream"},
    {"X-Format":"openapi"},
    {"X-Format":"swagger"},
    {"X-Format":"wsdl"},
    {"X-Format":"graphql"},
    {"Format":"event-stream"},
    {"Format":"sse"},
    {"Format":"protobuf"},
    {"Format":"msgpack"},
    {"Format":"grpc"},
    {"Format":"openapi"},
    {"Format":"swagger"},
    {"Format":"graphql"},
    {"Format":"html-partial"},
    {"Format":"fragment"},
    {"Format":"raw"},
    {"Format":"binary"},
    {"Content-Type":"text/event-stream"},
    {"Content-Type":"multipart/mixed"},
    {"Content-Type":"application/signed-exchange"},
    {"Content-Type":"application/webbundle"},
    {"Content-Type":"application/vnd.api+json; ext=bulk"},
    {"Content-Type":"application/vnd.api+json; profile=http://evil.com"},
    {"Content-Type":"application/json; profile=http://evil.com"},
    {"Content-Type":"application/json; schema=http://evil.com"},
    {"Content-Type":"text/html; boundary=evil"},
    {"Content-Type":"text/html; charset=invalid"},
    {"Content-Type":"text/html; charset=utf-7"},
    {"Content-Type":"text/html; charset=us-ascii"},
    {"Content-Type":"multipart/x-mixed-replace; boundary=evil"},
    {"X-Accept":"text/event-stream"},
    {"X-Accept":"multipart/mixed"},
    {"X-Accept":"application/signed-exchange"},
    {"X-Accept":"text/vnd.turbo-stream.html"},
    {"X-Accept":"application/health+json"},
    {"X-Response-Format":"event-stream"},
    {"X-Response-Format":"sse"},
    {"X-Response-Format":"protobuf"},
    {"X-Response-Format":"msgpack"},
    {"X-Response-Format":"grpc"},
    {"X-Response-Format":"openapi"},
    {"X-Response-Format":"fragment"},
    {"X-Response-Format":"partial"},
    {"X-Output":"event-stream"},
    {"X-Output":"sse"},
    {"X-Output":"protobuf"},
    {"X-Output":"msgpack"},
    {"X-Output":"grpc"},
    {"X-Output":"fragment"},
    {"X-Output":"partial"},
    {"X-Output":"raw"},
    {"Accept":"application/json"},
    {"Accept":"application/xml"},
    {"Accept":"text/xml"},
    {"Accept":"application/pdf"},
    {"Accept":"text/plain"},
    {"Accept":"application/xhtml+xml"},
    {"Accept":"application/rss+xml"},
    {"Accept":"application/atom+xml"},
    {"Accept":"text/csv"},
    {"Accept":"application/vnd.ms-excel"},
    {"Accept":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
    {"Accept":"application/msword"},
    {"Accept":"application/vnd.openxmlformats-officedocument.wordprocessingml.document"},
    {"Accept":"application/yaml"},
    {"Accept":"text/yaml"},
    {"Accept":"application/x-yaml"},
    {"Accept":"application/octet-stream"},
    {"Accept":"application/javascript"},
    {"Accept":"text/javascript"},
    {"Accept":"application/ld+json"},
    {"Accept":"application/x-ndjson"},
    {"Accept":"application/vnd.api+json"},
    {"Accept":"application/hal+json"},
    {"Accept":"application/problem+json"},
    {"Accept":"application/graphql+json"},
    {"Accept":"application/rtf"},
    {"Accept":"text/rtf"},
    {"Accept":"application/zip"},
    {"Accept":"application/x-tar"},
    {"Accept":"application/gzip"},
    {"Accept":"application/x-bzip2"},
    {"Accept":"application/x-7z-compressed"},
    {"Accept":"application/vnd.rar"},
    {"Accept":"image/png"},
    {"Accept":"image/jpeg"},
    {"Accept":"image/gif"},
    {"Accept":"image/webp"},
    {"Accept":"image/svg+xml"},
    {"Accept":"image/bmp"},
    {"Accept":"image/tiff"},
    {"Accept":"audio/mpeg"},
    {"Accept":"audio/ogg"},
    {"Accept":"audio/wav"},
    {"Accept":"audio/webm"},
    {"Accept":"video/mp4"},
    {"Accept":"video/mpeg"},
    {"Accept":"video/ogg"},
    {"Accept":"video/webm"},
    {"Accept":"application/vnd.ms-powerpoint"},
    {"Accept":"application/vnd.openxmlformats-officedocument.presentationml.presentation"},
    {"Accept":"application/vnd.oasis.opendocument.text"},
    {"Accept":"application/vnd.oasis.opendocument.spreadsheet"},
    {"Accept":"application/vnd.oasis.opendocument.presentation"},
    {"Accept":"application/x-httpd-php"},
    {"Accept":"application/x-sh"},
    {"Accept":"text/x-python"},
    {"Accept":"text/x-java-source"},
    {"Accept":"text/markdown"},
    {"Accept":"application/wasm"},
    {"Accept":"application/protobuf"},
    {"Accept":"application/msgpack"},
    {"Accept":"application/cbor"},
    {"Accept":"application/avro"},
    {"Accept":"application/x-amf"},
    {"Accept":"application/soap+xml"},
    {"Accept":"application/vnd.collection+json"},
    {"Accept":"application/vnd.github+json"},
    {"Accept":"application/vnd.api+json; version=1"},
    {"Accept":"application/ion"},
    {"Accept":"application/x-protobuf"},
    {"Accept":"application/x-msgpack"},
    {"Accept":"text/calendar"},
    {"Accept":"text/vcard"},
    {"Accept":"application/json; charset=utf-8"},
    {"Accept":"application/xml; charset=utf-8"},
    {"Accept":"*/*"},
    {"Accept":"application/json, text/plain, */*"},
    {"Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    {"Content-Type":"application/json"},
    {"Content-Type":"application/xml"},
    {"Content-Type":"text/xml"},
    {"Content-Type":"text/plain"},
    {"Content-Type":"application/x-www-form-urlencoded"},
    {"Content-Type":"multipart/form-data"},
    {"X-Format":"json"},
    {"X-Format":"xml"},
    {"X-Format":"pdf"},
    {"X-Format":"csv"},
    {"X-Format":"yaml"},
    {"Format":"json"},
    {"Format":"xml"},
    {"Format":"pdf"},
    {"Format":"csv"},
    {"Format":"yaml"},
    {"X-Accept":"application/json"},
    {"X-Accept":"application/xml"},
    {"X-Response-Format":"json"},
    {"X-Response-Format":"xml"},
    {"X-Response-Format":"pdf"},
    {"Accept-Profile":"application/json"},
    {"Accept-Profile":"application/xml"},
    {"X-Requested-With":"XMLHttpRequest"},
    {"X-Data-Format":"json"},
    {"X-Data-Format":"xml"},
    {"Response-Format":"json"},
    {"Response-Format":"xml"},
    {"API-Format":"json"},
    {"API-Format":"xml"},
    {"Output-Format":"json"},
    {"Output-Format":"xml"},
    {"Accept-Encoding":"gzip"},
    {"Accept-Encoding":"deflate"},
    {"Accept-Encoding":"br"},
    {"Accept-Encoding":"compress"},
    {"Accept-Encoding":"identity"},
    {"Accept-Encoding":"*"},
    {"Accept-Language":"en-US"},
    {"Accept-Language":"fr-FR"},
    {"Accept-Language":"es-ES"},
    {"Accept-Language":"de-DE"},
    {"Accept-Charset":"utf-8"},
    {"Accept-Charset":"iso-8859-1"},
    {"Accept-Charset":"windows-1252"},
    {"X-Output":"json"},
    {"X-Output":"xml"},
    {"X-Output":"pdf"},
    {"X-Return-Format":"json"},
    {"X-Return-Format":"xml"},
    {"X-Content-Format":"json"},
    {"X-Content-Format":"xml"},
    {"X-API-Version":"v1"},
    {"X-API-Version":"v2"},
    {"X-Media-Type":"json"},
    {"X-Media-Type":"xml"},
    {"Accept-Version":"1.0"},
    {"Accept-Version":"2.0"},
    {"X-Resource-Format":"json"},
    {"X-Resource-Format":"xml"},
    {"X-Preferred-Format":"json"},
    {"X-Preferred-Format":"xml"},
    {"X-Result-Format":"json"},
    {"X-Result-Format":"xml"},
    {"X-Export-Format":"csv"},
    {"X-Export-Format":"xlsx"},
    {"X-Download-Format":"pdf"},
    {"X-Download-Format":"csv"},
    {"Response-Type":"json"},
    {"Response-Type":"xml"},
    {"Output":"json"},
    {"Output":"xml"},
    {"Type":"json"},
    {"Type":"xml"},
    {"Datatype":"json"},
    {"Datatype":"xml"},
    {"Accept":"application/jsonlines"},
    {"Accept":"text/jsonlines"},
    {"Accept":"application/x-jsonlines"},
    {"Accept":"application/vnd.apache.parquet"},
    {"Accept":"application/x-parquet"},
    {"Accept":"application/vnd.apache.avro"},
    {"Accept":"application/x-avro-binary"},
    {"Accept":"application/vnd.openxmlformats-officedocument.spreadsheetml.template"},
    {"Accept":"application/vnd.ms-excel.sheet.macroEnabled.12"},
    {"Accept":"application/vnd.ms-excel.template.macroEnabled.12"},
    {"Accept":"application/x-sqlite3"},
    {"Accept":"application/sql"},
    {"Accept":"text/x-sql"},
    {"Accept":"application/x-ndjson"},
    {"Accept":"application/jsonl"},
    {"Accept":"application/x-ldjson"},
    {"Accept":"application/stream+json"},
    {"Accept":"application/x-bibtex"},
    {"Accept":"application/x-latex"},
    {"Accept":"text/x-tex"},
    {"Accept":"application/postscript"},
    {"Accept":"application/eps"},
    {"Accept":"image/x-eps"},
    {"Accept":"application/x-dvi"},
    {"Accept":"application/smil+xml"},
    {"Accept":"application/mathml+xml"},
    {"Accept":"application/xslt+xml"},
    {"Accept":"application/voicexml+xml"},
    {"Accept":"application/rdf+xml"},
    {"Accept":"application/sparql-results+xml"},
    {"Accept":"application/sparql-results+json"},
    {"Accept":"text/turtle"},
    {"Accept":"text/n3"},
    {"Accept":"application/n-triples"},
    {"Accept":"application/n-quads"},
    {"Accept":"application/trig"},
    {"Accept":"application/x-turtle"},
    {"Accept":"application/x-trig"},
    {"Accept":"application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\""},
    {"Accept":"application/activity+json"},
    {"Accept":"application/manifest+json"},
    {"Accept":"application/vnd.geo+json"},
    {"Accept":"application/geo+json"},
    {"Accept":"application/vnd.google-earth.kml+xml"},
    {"Accept":"application/vnd.google-earth.kmz"},
    {"Accept":"application/gpx+xml"},
    {"Accept":"application/toml"},
    {"Accept":"text/toml"},
    {"Accept":"application/x-toml"},
    {"Accept":"application/ini"},
    {"Accept":"text/x-ini"},
    {"Accept":"application/x-ini"},
    {"Accept":"application/properties"},
    {"Accept":"text/x-properties"},
    {"Accept":"application/x-java-properties"},
    {"Accept":"application/xliff+xml"},
    {"Accept":"application/x-gettext-translation"},
    {"Accept":"text/x-po"},
    {"Accept":"application/x-bittorrent"},
    {"Accept":"application/x-chess-pgn"},
    {"Accept":"application/x-chess-fen"},
    {"Accept":"application/x-research-info-systems"},
    {"Accept":"application/x-endnote-refer"},
    {"Accept":"application/marc"},
    {"Accept":"application/marcxml+xml"},
    {"Accept":"application/mods+xml"},
    {"Accept":"application/mets+xml"},
    {"Accept":"application/tei+xml"},
    {"Accept":"application/jats+xml"},
    {"Accept":"application/docbook+xml"},
    {"Accept":"application/x-dtbncx+xml"},
    {"Accept":"application/epub+zip"},
    {"Accept":"application/x-mobipocket-ebook"},
    {"Accept":"application/vnd.amazon.ebook"},
    {"Accept":"application/x-ibooks+zip"},
    {"Accept":"application/x-sony-bbeb"},
    {"Accept":"application/vnd.openxmlformats-officedocument.presentationml.template"},
    {"Accept":"application/vnd.ms-powerpoint.template.macroEnabled.12"},
    {"Accept":"application/vnd.ms-powerpoint.slideshow.macroEnabled.12"},
    {"Accept":"application/vnd.openxmlformats-officedocument.wordprocessingml.template"},
    {"Accept":"application/vnd.ms-word.document.macroEnabled.12"},
    {"Accept":"application/vnd.ms-word.template.macroEnabled.12"},
    {"Accept":"application/vnd.visio"},
    {"Accept":"application/vnd.ms-project"},
    {"Accept":"application/x-iwork-pages-sffpages"},
    {"Accept":"application/x-iwork-numbers-sffnumbers"},
    {"Accept":"application/x-iwork-keynote-sffkey"},
    {"Accept":"application/x-abiword"},
    {"Accept":"application/x-gnumeric"},
    {"Accept":"application/x-kpresenter"},
    {"Accept":"application/x-kword"},
    {"Accept":"application/x-kspread"},
    {"Accept":"application/vnd.stardivision.writer"},
    {"Accept":"application/vnd.stardivision.calc"},
    {"Accept":"application/vnd.stardivision.impress"},
    {"Accept":"application/vnd.sun.xml.writer"},
    {"Accept":"application/vnd.sun.xml.calc"},
    {"Accept":"application/vnd.sun.xml.impress"},
    {"Accept":"application/vnd.corel-draw"},
    {"Accept":"application/vnd.wordperfect"},
    {"Accept":"application/vnd.lotus-1-2-3"},
    {"Accept":"application/vnd.lotus-wordpro"},
    {"Accept":"application/vnd.framemaker"},
    {"Accept":"application/x-tex-tfm"},
    {"Accept":"application/x-texinfo"},
    {"Accept":"application/x-dvi"},
    {"Accept":"application/x-font-ttf"},
    {"Accept":"application/x-font-woff"},
    {"Accept":"application/font-woff"},
    {"Accept":"application/font-woff2"},
    {"Accept":"application/vnd.ms-fontobject"},
    {"Accept":"application/x-font-otf"},
    {"Accept":"application/x-font-type1"},
    {"X-Format":"jsonlines"},
    {"X-Format":"ndjson"},
    {"X-Format":"parquet"},
    {"X-Format":"avro"},
    {"X-Format":"sqlite"},
    {"X-Format":"sql"},
    {"X-Format":"toml"},
    {"X-Format":"ini"},
    {"X-Format":"properties"},
    {"X-Format":"rdf"},
    {"X-Format":"turtle"},
    {"X-Format":"n3"},
    {"X-Format":"ntriples"},
    {"X-Format":"jsonld"},
    {"X-Format":"geojson"},
    {"X-Format":"kml"},
    {"X-Format":"gpx"},
    {"X-Format":"bibtex"},
    {"X-Format":"latex"},
    {"X-Format":"tex"},
    {"X-Format":"epub"},
    {"X-Format":"mobi"},
    {"X-Format":"docx"},
    {"X-Format":"xlsx"},
    {"X-Format":"pptx"},
    {"X-Format":"odt"},
    {"X-Format":"ods"},
    {"X-Format":"odp"},
    {"X-Format":"woff"},
    {"X-Format":"ttf"},
    {"X-Format":"otf"},
    {"Format":"jsonlines"},
    {"Format":"ndjson"},
    {"Format":"parquet"},
    {"Format":"avro"},
    {"Format":"sql"},
    {"Format":"toml"},
    {"Format":"ini"},
    {"Format":"rdf"},
    {"Format":"geojson"},
    {"Format":"kml"},
    {"Format":"latex"},
    {"Format":"epub"},
    {"Content-Type":"application/jsonlines"},
    {"Content-Type":"text/jsonlines"},
    {"Content-Type":"application/toml"},
    {"Content-Type":"application/sql"},
    {"Content-Type":"application/x-sqlite3"},
    {"Content-Type":"application/rdf+xml"},
    {"Content-Type":"text/turtle"},
    {"Content-Type":"application/ld+json"},
    {"Content-Type":"application/geo+json"},
    {"Content-Type":"application/gpx+xml"},
    {"Content-Type": "application/json-patch+json"},       
    {"Content-Type": "application/merge-patch+json"},      
    {"Content-Type": "application/problem+json"},
    {"Content-Type": "application/ld+json"},               
    {"Content-Type": "application/hal+json"},
    {"Content-Type": "application/vnd.api+json"},          
    {"Content-Type": "application/scim+json"},             
    {"Content-Type": "application/activity+json"},         
    {"Content-Type": "application/fhir+json"},             
    {"Content-Type": "application/x-yaml"},
    {"Content-Type": "text/yaml"},
    {"Content-Type": "application/graphql"},               
    {"Content-Type": "application/xml; charset=invalid"},
    {"X-Accept":"application/jsonlines"},
    {"X-Accept":"application/parquet"},
    {"X-Accept":"application/avro"},
    {"X-Accept":"application/sql"},
    {"X-Accept":"application/toml"},
    {"X-Accept":"text/csv"},
    {"X-Accept":"application/rdf+xml"},
    {"X-Accept":"application/geo+json"},
    {"X-Response-Format":"jsonlines"},
    {"X-Response-Format":"ndjson"},
    {"X-Response-Format":"parquet"},
    {"X-Response-Format":"sql"},
    {"X-Response-Format":"toml"},
    {"X-Response-Format":"rdf"},
    {"X-Response-Format":"geojson"},
    {"X-Response-Format":"latex"},
    {"X-Output":"jsonlines"},
    {"X-Output":"ndjson"},
    {"X-Output":"parquet"},
    {"X-Output":"avro"},
    {"X-Output":"sql"},
    {"X-Output":"toml"},
    {"X-Output":"rdf"},
    {"X-Output":"latex"},
    {"X-Output":"epub"},
    {"X-Return-Format":"jsonlines"},
    {"X-Return-Format":"parquet"},
    {"X-Return-Format":"sql"},
    {"X-Return-Format":"toml"},
    {"X-Return-Format":"rdf"},
    {"X-Content-Format":"jsonlines"},
    {"X-Content-Format":"parquet"},
    {"X-Content-Format":"sql"},
    {"X-Content-Format":"toml"},
    {"X-Media-Type":"jsonlines"},
    {"X-Media-Type":"parquet"},
    {"X-Media-Type":"sql"},
    {"X-Media-Type":"toml"},
    {"X-Resource-Format":"jsonlines"},
    {"X-Resource-Format":"parquet"},
    {"X-Resource-Format":"sql"},
    {"X-Preferred-Format":"jsonlines"},
    {"X-Preferred-Format":"parquet"},
    {"X-Preferred-Format":"sql"},
    {"X-Result-Format":"jsonlines"},
    {"X-Result-Format":"parquet"},
    {"X-Result-Format":"sql"},
    {"X-Export-Format":"jsonlines"},
    {"X-Export-Format":"ndjson"},
    {"X-Export-Format":"parquet"},
    {"X-Export-Format":"sql"},
    {"X-Export-Format":"toml"},
    {"X-Export-Format":"bibtex"},
    {"X-Export-Format":"latex"},
    {"X-Download-Format":"jsonlines"},
    {"X-Download-Format":"parquet"},
    {"X-Download-Format":"sql"},
    {"X-Download-Format":"toml"},
    {"X-Download-Format":"epub"},
    {"X-Download-Format":"mobi"},
    {"X-Download-Format":"docx"},
    {"X-Download-Format":"odt"},
    {"Response-Type":"jsonlines"},
    {"Response-Type":"parquet"},
    {"Response-Type":"sql"},
    {"Response-Type":"toml"},
    {"Output":"jsonlines"},
    {"Output":"parquet"},
    {"Output":"sql"},
    {"Output":"toml"},
    {"Type":"jsonlines"},
    {"Type":"parquet"},
    {"Type":"sql"},
    {"Type":"toml"},
    {"Datatype":"jsonlines"},
    {"Datatype":"parquet"},
    {"Datatype":"sql"},
    {"Datatype":"toml"},
    {"Accept-Profile":"application/parquet"},
    {"Accept-Profile":"application/avro"},
    {"Accept-Profile":"application/sql"},
    {"X-Data-Format":"jsonlines"},
    {"X-Data-Format":"parquet"},
    {"X-Data-Format":"sql"},
    {"X-Data-Format":"toml"},
    {"Response-Format":"jsonlines"},
    {"Response-Format":"parquet"},
    {"Response-Format":"sql"},
    {"API-Format":"jsonlines"},
    {"API-Format":"parquet"},
    {"API-Format":"sql"},
    {"Output-Format":"jsonlines"},
    {"Output-Format":"parquet"},
    {"Output-Format":"sql"},
    {"Accept-Encoding":"application/x-protobuf"},
    {"Accept-Encoding":"application/x-msgpack"},
    {"Accept-Charset":"application/x-yaml"},
    {"X-Serialize":"protobuf"},
    {"X-Serialize":"msgpack"},
    {"X-Serialize":"cbor"},
    {"X-Serialize":"bson"},
    {"X-Serialize":"ion"},
    {"X-Serialize":"smile"},
    {"X-Encoding":"protobuf"},
    {"X-Encoding":"msgpack"},
    {"X-Encoding":"cbor"},
    {"X-Encoding":"avro"},
    {"Serialization":"protobuf"},
    {"Serialization":"msgpack"},
    {"Serialization":"cbor"},
    {"Serialization":"bson"},
    {"X-Serializer":"protobuf"},
    {"X-Serializer":"msgpack"},
    {"X-Serializer":"json"},
    {"X-Serializer":"xml"},
    {"Accept":"application/x-protobuf"},
    {"Accept":"application/protobuf"},
    {"Accept":"application/vnd.google.protobuf"},
    {"Accept":"application/x-msgpack"},
    {"Accept":"application/msgpack"},
    {"Accept":"application/vnd.msgpack"},
    {"Accept":"application/cbor"},
    {"Accept":"application/x-cbor"},
    {"Accept":"application/bson"},
    {"Accept":"application/x-bson"},
    {"Accept":"application/ion"},
    {"Accept":"application/x-ion"},
    {"Accept":"application/smile"},
    {"Accept":"application/x-smile"},
    {"Accept":"application/thrift"},
    {"Accept":"application/x-thrift"},
    {"Accept":"application/x-capnp"},
    {"Accept":"application/flatbuffers"},
    {"Accept":"application/x-flatbuffers"},
    {"Accept":"application/x-yaml"},
    {"Accept":"text/yaml"},
    {"Accept":"text/x-yaml"},
    {"Accept":"application/x-hjson"},
    {"Accept":"application/hjson"},
    {"Accept":"application/json5"},
    {"Accept":"text/json5"},
    {"Accept":"application/hocon"},
    {"Accept":"application/x-hocon"},
    {"Accept":"application/cue"},
    {"Accept":"application/x-cue"},
    {"Accept":"application/dhall"},
    {"Accept":"application/x-pkl"},
    {"Accept":"application/pkl"},
    {"Accept":"application/vnd.api+json"},
    {"Accept":"application/hal+json"},
    {"Accept":"application/vnd.siren+json"},
    {"Accept":"application/vnd.collection+json"},
    {"Accept":"application/json-patch+json"},
    {"Accept":"application/merge-patch+json"},
    {"Accept":"application/json-seq"},
    {"Accept":"application/graphql"},
    {"Accept":"application/graphql+json"},
    {"Accept":"application/graphql-response+json"},
    {"X-GraphQL-Format":"json"},
    {"X-GraphQL-Format":"cbor"},
    {"X-Requested-With":"Protobuf"},
    {"X-Requested-With":"MessagePack"},
    {"X-Response-Encoding":"protobuf"},
    {"X-Response-Encoding":"msgpack"},
    {"X-Response-Encoding":"cbor"},
    {"X-Wire-Format":"protobuf"},
    {"X-Wire-Format":"grpc"},
    {"X-Wire-Format":"thrift"},
    {"X-Transport":"protobuf"},
    {"X-Transport":"msgpack"},
    {"X-Protocol":"grpc"},
    {"X-Protocol":"grpc-web"},
    {"X-Protocol":"thrift"},
    {"Accept":"application/grpc"},
    {"Accept":"application/grpc+proto"},
    {"Accept":"application/grpc-web"},
    {"Accept":"application/grpc-web+proto"},
    {"Accept":"application/grpc-web-text"},
    {"Accept":"application/grpc-web-text+proto"},
    {"Content-Type":"application/grpc"},
    {"Content-Type":"application/grpc-web"},
    {"Accept":"application/x-hdf"},
    {"Accept":"application/x-hdf5"},
    {"Accept":"application/x-netcdf"},
    {"Accept":"application/x-fits"},
    {"Accept":"application/x-matlab-data"},
    {"Accept":"application/x-numpy"},
    {"Accept":"application/x-arrow"},
    {"Accept":"application/vnd.apache.arrow.file"},
    {"Accept":"application/vnd.apache.arrow.stream"},
    {"Accept":"application/x-feather"},
    {"Accept":"application/x-pickle"},
    {"X-Render-As":"json"},
    {"X-Render-As":"xml"},
    {"X-Render-As":"csv"},
    {"X-Render-As":"yaml"},
    {"X-View":"json"},
    {"X-View":"xml"},
    {"X-View":"raw"},
    {"X-View":"source"},
    {"X-Transform":"json"},
    {"X-Transform":"xml"},
    {"X-Transform":"yaml"},
    {"X-Convert-To":"json"},
    {"X-Convert-To":"xml"},
    {"X-Convert-To":"csv"},
    {"X-Representation":"json"},
    {"X-Representation":"xml"},
    {"X-Representation":"binary"},
    {"Prefer":"return=representation"},
    {"Prefer":"respond-async"},
    {"Prefer":"return=minimal"},
    {"X-Pretty":"true"},
    {"X-Pretty-Print":"true"},
    {"X-Indent":"true"},
    {"Accept":"application/atom+xml"},
    {"Accept":"application/rss+xml"},
    {"Accept":"application/feed+json"},
    {"Accept":"application/json-feed"},
    {"Accept":"application/x-msgpack+gzip"},
    {"Accept":"application/x-protobuf+snappy"},
    {"Accept":"application/x-protobuf+lz4"},
    {"Accept": "application/json\u000bContent-Type: text/javascript"},
    {"Accept": "application/json\u000cContent-Type: text/html"},
    {"Accept": "application/json;q=0"},
    {"Accept": "application/json;q=1.0"},
    {"Accept": "application/json;q=1.1"},
    {"Accept": "application/json;q=-1"},
    {"Accept": "application/json;q="},
    {"Accept": "application/json;q=0.000"},
    {"Accept": "text/html;q=0, */*;q=0"},
    {"Accept": "application/json;q=0.001"},
    {"Accept": "*/*;q=0"},
    {"Accept": "*/json"},
    {"Accept": "application/*+json"},
    {"Accept": "*"},
    {"Accept": ""},
    {"Accept": ","},
    {"Accept": "application/json,"},
    {"Accept": ",application/json"},
    {"Accept": "application/json\u0000"},
    {"Accept": "application/json\u000b"},
    {"Accept": "application/json\u000c"},
    {"Accept": "application/json\u0085"},
    {"Accept": "application/json\u00a0"},
    {"Accept": "application/json", "Accept": "text/html"},
    {"Accept": "application/json", "accept": "text/html"},
    {"Accept": "application/json", "ACCEPT": "text/html"},
    {"Accept": "application/json", "Accept": "application/json"},
    {"Accept": "application/json"},
    {"ACCEPT": "application/json"},
    {"Accept":"application/x-empty"},
    {"Accept":"application/void"},
    {"Accept":"application/null"},
    {"Accept":"text/void"},
    {"Accept":"text/null"},
    {"Accept":"text/empty"},
    {"Accept":"none/none"},
    {"Accept":"application/none"},
    {"Accept":"/"},
    {"Accept":"./"},
    {"Accept":"../html"},
    {"Accept":"text/"},
    {"Accept":"/html"},
    {"Accept":"text/html;charset=utf-7"},
    {"Accept":"text/html;charset=utf-32be"},
    {"Accept":"text/html;charset=utf-32le"},
    {"Accept":"text/html;charset=cp437"},
    {"Accept":"text/html;charset=ebcdic"},
    {"Accept":"text/html;charset=iso-2022-jp"},
    {"Accept":"text/html;charset=gb18030"},
    {"Accept":"text/html;charset=big5"},
    {"Accept":"text/html;charset=koi8-r"},
    {"Accept":"text/html;charset=macintosh"},
    {"Accept":"text/html;charset=x-mac-cyrillic"},
    {"Accept":"text/html;version=2.0"},
    {"Accept":"text/html;version=3.2"},
    {"Accept":"text/html;version=5.0"},
    {"Accept":"text/html;level=0"},
    {"Accept":"text/html;level=99"},
    {"Accept":"text/html;profile=mobile"},
    {"Accept":"text/html;profile=amp"},
    {"Accept":"text/html;profile=lite"},
    {"Accept":"text/html;profile=print"},
    {"Accept":"text/html;profile=embed"},
    {"Accept":"text/html;profile=reader"},
    {"Accept":"text/html;profile=accessibility"},
    {"Accept":"text/html;type=partial"},
    {"Accept":"text/html;type=fragment"},
    {"Accept":"text/html;type=component"},
    {"Accept":"text/html;type=shell"},
    {"Accept":"text/html;type=skeleton"},
    {"Accept":"text/html;type=raw"},
    {"Accept":"text/html;type=source"},
    {"Accept":"text/html;render=server"},
    {"Accept":"text/html;render=client"},
    {"Accept":"text/html;render=static"},
    {"Accept":"text/html;render=none"},
    {"Accept":"text/html;features=nojs"},
    {"Accept":"text/html;features=nocss"},
    {"Accept":"text/html;features=noimages"},
    {"X-Original-Accept":"text/wml"},
    {"X-Original-Accept":"text/vnd.wap.wml"},
    {"Accept":"text/vnd.wap.wml"},
    {"Accept":"text/vnd.wap.wmlscript"},
    {"Accept":"application/vnd.wap.wmlc"},
    {"Accept":"application/vnd.wap.wmlscriptc"},
    {"Accept":"application/vnd.wap.xhtml+xml"},
    {"Accept":"application/vnd.wap.connectivity-wbxml"},
    {"Accept":"application/vnd.wap.multipart.mixed"},
    {"Accept":"application/vnd.wap.multipart.related"},
    {"Accept":"text/hdml"},
    {"Accept":"application/x-hdmlc"},
    {"Accept":"text/x-thinlinc"},
    {"Accept":"application/x-silverlight"},
    {"Accept":"application/x-shockwave-flash"},
    {"Accept":"application/x-director"},
    {"Accept":"application/x-java-applet"},
    {"Accept":"application/x-java-jnlp-file"},
    {"Accept":"application/xhtml+xml;profile=mobile"},
    {"Accept":"application/xhtml+xml;profile=basic"},
    {"Accept":"application/xhtml+xml;profile=c-html"},
    {"Accept":"application/json; profile=compact"},
    {"Accept":"application/json; profile=verbose"},
    {"Accept":"application/json; profile=minimal"},
    {"Accept":"application/json; profile=full"},
    {"Accept":"application/json; profile=representation"},
    {"Accept":"application/json; odata=verbose"},
    {"Accept":"application/json; odata=minimalmetadata"},
    {"Accept":"application/json; odata=fullmetadata"},
    {"Accept":"application/json; odata=nometadata"},
    {"Accept":"application/json; odata.metadata=minimal"},
    {"Accept":"application/json; odata.metadata=full"},
    {"Accept":"application/json; odata.metadata=none"},
    {"Accept":"application/json; odata.streaming=true"},
    {"Accept":"application/json; odata.streaming=false"},
    {"Accept":"application/json; IEEE754Compatible=true"},
    {"Accept":"application/vnd.api+json; ext=\"https://jsonapi.org/ext/atomic\""},
    {"Accept":"application/vnd.api+json; ext=\"https://evil.com\""},
    {"Accept":"application/vnd.api+json; profile=\"https://evil.com\""},
    {"Accept":"application/hal+json; profile=embedded"},
    {"Accept":"application/hal+json; profile=links-only"},
    {"Accept":"application/json; profile=\"urn:example:minimal\""},
    {"Accept":"application/json; profile=\"urn:example:verbose\""},
    {"Accept":"application/vnd.api+form"},
    {"Accept":"application/x-www-form-urlencoded+json"},
    {"Accept":"application/hal+form+json"},
    {"Accept":"application/pkcs7-signature"},
    {"Accept":"application/pkcs12"},
    {"Accept":"application/x-pkcs12"},
    {"Accept":"application/cms"},
    {"Accept":"application/cose-key"},
    {"Accept":"application/cose-key-set"},
    {"Accept":"application/cwt"},
    {"Accept":"application/at+jwt"},
    {"Accept":"application/token-introspection+jwt"},
    {"Accept":"application/logout+jwt"},
    {"Accept":"application/secevent+jwt"},
    {"Accept":"application/dpop+jwt"},
    {"Accept":"application/oauth-authz-req+jwt"},
    {"Accept":"application/vnd.apple.pkpass"},
    {"Accept":"application/vnd.google.safetynet.token"},
    {"Accept":"text/html text/plain"},
    {"Accept":"text/html|text/plain"},
    {"Accept":"text/html;text/plain"},
    {"Accept":"text/html&text/plain"},
    {"Accept":"text/html+text/plain"},
    {"Accept":"[text/html]"},
    {"Accept":"(text/html)"},
    {"Accept":"<text/html>"},
    {"Accept":"\"text/html\""},
    {"Accept":"'text/html'"},
    {"Accept":"text/html\x00application/json"},
    {"Accept":"text/html\napplication/json"},
    {"Accept":"text/html\rapplication/json"},
    {"Accept":"text/html\r\napplication/json"},
    {"Accept":"application/senml+json"},
    {"Accept":"application/senml+cbor"},
    {"Accept":"application/senml+xml"},
    {"Accept":"application/senml-etch+json"},
    {"Accept":"application/senml-etch+cbor"},
    {"Accept":"application/coap-group+json"},
    {"Accept":"application/coapapplication"},
    {"Accept":"application/dots+cbor"},
    {"Accept":"application/ace+json"},
    {"Accept":"application/ace+cbor"},
    {"Accept":"application/td+json"},
    {"Accept":"application/tm+json"},
    {"Accept":"application/wot-thing-description+json"},
    {"Accept":"application/vnd.apple.mpegurl"},
    {"Accept":"application/vnd.apple.installer+xml"},
    {"Accept":"application/vnd.openbanking.v3+json"},
    {"Accept":"application/vnd.openbanking.v4+json"},
    {"Accept":"application/vnd.bsi.openbanking.v1+json"},
    {"Accept":"application/pem-certificate-chain"},
    {"Accept":"application/vnd.stripe.v1+json"},
    {"Accept":"application/vnd.paypal.v1+json"},
    {"Accept":"text/html;boundary=evil"},
    {"Accept":"application/json;boundary=evil"},
    {"Accept":"text/plain;boundary=----WebKitFormBoundary"},
    {"Accept":"*/*;boundary=evil"},
    {"Accept":"application/x-handlebars"},
    {"Accept":"application/x-mustache"},
    {"Accept":"text/x-handlebars-template"},
    {"Accept":"text/x-mustache-template"},
    {"Accept":"application/x-velocity"},
    {"Accept":"application/x-freemarker"},
    {"Accept":"application/x-thymeleaf"},
    {"Accept":"application/x-jinja2"},
    {"Accept":"application/x-twig"},
    {"Accept":"application/x-razor"},
    {"Accept":"application/x-blade"},
    {"Accept":"application/x-ejs"},
    {"Accept":"application/x-pug"},
    {"Accept":"application/x-slim"},
    {"Accept":"application/x-haml"},
    {"Accept":"application/x-erb"},
    {"Accept":"application/vnd.api+json; version=0"},
    {"Accept":"application/vnd.api+json; version=-1"},
    {"Accept":"application/vnd.api+json; version=99"},
    {"Accept":"application/vnd.api+json; version="},
    {"Accept":"application/vnd.api+json; version=null"},
    {"Accept":"application/vnd.api+json; version=undefined"},
    {"Accept":"application/json; v=1"},
    {"Accept":"application/json; v=2"},
    {"Accept":"application/json; api=v1"},
    {"Accept":"application/json; api=v2"},
    {"Accept":"application/json; revision=latest"},
    {"Accept":"application/json; revision=draft"},
    {"Accept":"application/problem+json; type=about:blank"},
    {"Accept":"application/problem+json; type=urn:error:not-found"},
    {"Accept":"application/problem+xml; type=about:blank"},
    {"Accept":"application/vnd.error+json; logref=true"},
    {"Accept":"application/json; error-format=verbose"},
    {"Accept":"application/json; debug=true"},
    {"Accept":"application/json; trace=true"},
    {"Accept":"application/json; include=stacktrace"},
    {"Accept":"application/json; include=message,trace,errors"},
    {"Accept":"*/*;q=1, text/*;q=0, text/html;q=0"},
    {"Accept":"text/*;q=1, text/html;q=0"},
    {"Accept":"application/*;q=1, application/json;q=0"},
    {"Accept":"*/*;q=1, text/html;q=0"},
    {"Accept":"*/*;q=0.001, text/html;q=0"},
    {"Accept":"text/*;q=0.001, text/html;q=0, */*;q=0"},
    {"Accept":"text%2Fhtml"},
    {"Accept":"text/ht%6Dl"},
    {"Accept":"text\u200B/html"},
    {"Accept":"text\uFEFF/html"},
    {"Accept":"text/htm\u0300l"},
    {"Accept":"\u202Etext/html"},
    {"Accept":"text/html\u202E"},
    {"Accept":"text\u2060/\u2060html"},
    {"Accept":"text/html (standard web page)"},
    {"Accept":"text/html (evil comment)"},
    {"Accept":"(comment) text/html"},
    {"Accept":"text/(comment)html"},
    {"Accept":"text/html;q=0.001, application/json;q=1"},
    {"Accept":"text/html; ext=\"bulk\""},
    {"Accept":"text/html; boundary=something"},
    {"Accept":"text/html\r\n"},
    {"Accept":"text/html\t"},
    {"Accept":"  text/html  "},
    {"Accept":"TEXT/HTML"},
    {"Accept":"Text/Html"},
    {"Accept":"application/vnd.github.v3+json"},
    {"Accept":"application/vnd.github.v3.raw"},
    {"Accept":"application/vnd.github.v3.text+json"},
    {"Accept":"application/vnd.github.v3.html+json"},
    {"Accept":"application/vnd.github.v3.full+json"},
    {"Accept":"application/vnd.github.v3.diff"},
    {"Accept":"application/vnd.github.v3.patch"},
    {"Accept":"application/vnd.github.raw+json"},
    {"Accept":"application/vnd.github.object"},
    {"Accept":"application/vnd.heroku+json; version=3"},
    {"Accept":"application/vnd.cloudflare+json"},
    {"Accept":"application/vnd.kubernetes.protobuf"},
    {"Accept":"application/vnd.kubernetes.protobuf;stream=watch"},
    {"Accept":"application/json;stream=watch"},
    {"Accept":"application/vnd.docker.distribution.manifest.list.v2+json"},
    {"Accept":"application/vnd.docker.raw-stream"},
    {"Accept":"application/vnd.gitlab.v4+json"},
    {"Accept":"application/vnd.bitbucket.v2+json"},
    {"Accept":"application/vnd.atlassian+json"},
    {"Accept":"application/vnd.oracle.resource+json"},
    {"Accept":"application/vnd.oracle.adf.batch+json"},
    {"Accept":"application/vnd.vmware.vcloud+xml"},
    {"Accept":"application/vnd.aws.restjson"},
    {"Accept":"application/vnd.siren+json"},
    {"Accept":"application/json-home"},
    {"Accept":"application/webthing+json"},
    {"Accept":"application/vnd.restful+json"},
    {"Accept":"application/jrd+json"},
    {"Accept":"application/xrd+xml"},
    {"Accept":"application/webfinger+json"},
    {"Accept":"application/nodeinfo+json"},
    {"Accept":"application/host-meta+json"},
    {"Accept":"application/host-meta+xml"},
    {"Accept":"text/event-stream; charset=utf-8"},
    {"Accept":"text/event-stream, text/html"},
    {"Accept":"application/x-ndjson, text/event-stream"},
    {"Accept":"application/stream+json, text/event-stream"},
    {"Accept":"text/event-stream;q=1, text/html;q=0"},
    {"Accept":"application/json;charset=utf-8;boundary=evil"},
    {"Accept":"application/json; indent=4"},
    {"Accept":"application/json; envelope=true"},
    {"Accept":"application/json; fields=id,name"},
    {"Accept":"application/json; version=2"},
    {"Accept":"application/json; format=pretty"},
    {"Accept":"application/json; callback=fn"},
    {"Accept":"application/json; flat=true"},
    {"Accept":"application/json; naked=true"},
    {"Accept":"application/json; raw=true"},
    {"Accept":"text/html;q=0.9, application/json;q=0.9, */*;q=0.8"},
    {"Accept":"text/html;q=NaN"},
    {"Accept":"text/html;q=Infinity"},
    {"Accept":"text/html;q=1e1"},
    {"Accept":"text/html;q=0x1"},
    {"Accept":"text/html;q=1.0000000000000001"},
    {"Accept":"text/html;q=0;q=1"},
    {"Accept":"text/html;foo=bar;baz=qux"},
    {"Accept":"text/html;ext=evil.com"},
    {"Accept":"text/html;profile=https://evil.com"},
    {"Accept":"text/html;type=entry"},
    {"Accept":"."},
    {"Accept":"..."},
    {"Accept":"text"},
    {"Accept":"text/"},
    {"Accept":"/html"},
    {"Accept":"text//html"},
    {"Accept":"text/ html"},
    {"Accept":"text /html"},
    {"Accept":" "},
    {"Accept":"\t"},
    {"Accept":"application/json;"},
    {"Accept":"application/json;;"},
    {"Accept":"application/json;="},
    {"Accept":"application/json;q"},
    {"Accept":"application/json;q=;"},
    {"Accept":"text/html, , application/json"},
    {"Accept":"application/x-sas"},
    {"Accept":"application/x-stata"},
    {"Accept":"application/x-spss-sav"},
    {"Accept":"application/x-r-data"},
    {"Accept":"application/x-sas7bdat"},
    {"Accept":"chemical/x-cml"},
    {"Accept":"chemical/x-mol"},
    {"Accept":"chemical/x-pdb"},
    {"Accept":"application/vnd.wolfram.mathematica"},
    {"Accept":"application/x-jupyter+json"},
    {"Accept":"application/vnd.drupal.ajax"},
    {"Accept":"application/vnd.wordpress.v2+json"},
    {"Accept":"application/vnd.contentful.management.v1+json"},
    {"Accept":"application/vnd.contentful.delivery.v1+json"},
    {"Accept":"application/vnd.strapi.v4+json"},
    {"Accept":"application/vnd.shopify.v1+json"},
    {"Accept":"application/vnd.magento.v1+json"},
    {"Accept":"application/vnd.sitecore+json"},
    {"Accept":"application/vnd.aem.page+json"},
    {"Accept":"application/vnd.liferay+json"},
    {"Accept":"application/xhtml+xml;profile=c-html"},
    {"Accept":"application/x-component"},
    {"Accept":"text/x-gwt-rpc"},
    {"Accept":"application/x-gwt-rpc"},
    {"Accept":"application/dart"},
    {"Accept":"application/x-silverlight-app"},
    {"Accept":"application/x-pem-file"},
    {"Accept":"application/pkcs7-mime"},
    {"Accept":"application/pkcs8"},
    {"Accept":"application/pkcs10"},
    {"Accept":"application/pkix-cert"},
    {"Accept":"application/pkix-crl"},
    {"Accept":"application/x-x509-ca-cert"},
    {"Accept":"application/x-x509-user-cert"},
    {"Accept":"application/scep"},
    {"Accept":"application/timestamp-query"},
    {"Accept":"application/timestamp-reply"},
    {"Accept":"application/ocsp-request"},
    {"Accept":"application/ocsp-response"},
    {"Accept":"text/html;q=0, application/json;q=0, */*;q=0.001"},
    {"Accept":"text/html;q=0, */*"},
    {"Accept":"application/xml;q=1, text/html;q=0"},
    {"Accept":"image/webp;q=1, text/html;q=0, */*;q=0"},
    {"Accept":"application/octet-stream;q=1, text/html;q=0"},
    {"Accept":"text/plain;q=1, text/html;q=0, */*;q=0"},
    {"Accept":"application/pdf;q=1, text/html;q=0"},
    {"Accept":"text/html;q=1;mxb=100000"},
    {"Accept":"text/html;q=1;mxt=5000"},
    {"Accept":"text/html;q=0.9;ext=evil"},
    {"Accept":"text/html;q=1;level=1;foo=bar"},
    {"Accept":"text/html;level=1"},
    {"Accept":"text/html;level=2"},
    {"Accept":"text/html;level=3"},
    {"Accept":"text/html;level=1;q=0.7, text/html;level=2;q=0.4, */*;q=0.5"},
    {"Accept":"application/*+json"},
    {"Accept":"application/*+xml"},
    {"Accept":"application/*+zip"},
    {"Accept":"application/*+cbor"},
    {"Accept":"application/*+yaml"},
    {"Accept":"application/*+ber"},
    {"Accept":"application/*+der"},
    {"Accept":"application/*+fastinfoset"},
    {"Accept":"application/*+wbxml"},
    {"Accept":"image/*+xml"},
    {"Accept":"model/*+xml"},
    {"Accept":"model/*+json"},
    {"Accept":"message/http"},
    {"Accept":"message/partial"},
    {"Accept":"message/external-body"},
    {"Accept":"message/global"},
    {"Accept":"multipart/byteranges"},
    {"Accept":"multipart/byteranges; boundary=evil"},
    {"Accept":"text/html;q=0"},
    {"Accept":"text/html;q=0, application/xhtml+xml;q=0"},
    {"Accept":"text/html;q=0, */*;q=0.001"},
    {"Accept":"*/*;q=0, text/html;q=0"},
    {"Accept":"application/problem+json"},
    {"Accept":"application/problem+xml"},
    {"Accept":"application/problem+json, text/html;q=0"},
    {"Accept":"application/json;charset=utf-8"},
    {"Accept":"application/json;charset=utf-16"},
    {"Accept":"application/json;charset=iso-8859-1"},
    {"Accept":"application/xml;charset=utf-16be"},
    {"Accept":"text/plain;charset=ebcdic-us"},
    {"Accept":"application/signed-exchange;v=b3;q=0.9, text/html"},
    {"Accept":"application/signed-exchange;v=b3"},
    {"Accept":"application/signed-exchange;v=b2"},
    {"Accept":"application/webbundle;v=b2"},
    {"Accept":"application/json;q=0.9, application/xml;q=0.9"},
    {"Accept":"text/html;q=0.9, application/xhtml+xml;q=0.9, application/json;q=0.9"},
    {"Accept":"text/html;q=1, application/json;q=1, application/xml;q=1"},
    {"Accept":"text/html;charset=utf-8;q=0.9;level=1"},
    {"Accept":"text/html;boundary=something;q=1"},
    {"Accept":"application/json;version=2;q=0.8"},
    {"Accept":"application/json;api-version=3;q=1"},
    {"Accept":"text/html;q=0.9;charset=utf-8"},
    {"Accept":"multipart/form-data"},
    {"Accept":"multipart/form-data; boundary=----evil"},
    {"Accept":"application/x-www-form-urlencoded"},
    {"Accept":"text/html+json"},
    {"Accept":"text/html+xml"},
    {"Accept":"text/csv+json"},
    {"Accept":"image/png+xml"},
    {"Accept":"text/plain+json"},
    {"Accept":"application/pdf+json"},
    {"Accept":"audio/mpeg+json"},
    {"Accept":"text/*"},
    {"Accept":"application/*"},
    {"Accept":"image/*"},
    {"Accept":"audio/*"},
    {"Accept":"video/*"},
    {"Accept":"message/*"},
    {"Accept":"multipart/*"},
    {"Accept":"font/*"},
    {"Accept":"model/*"},
    {"Accept":"*/html"},
    {"Accept":"*/json"},
    {"Accept":"*/xml"},
    {"Accept":"*/plain"},
    {"Accept":"*/pdf"},
    {"Accept":"text/html;charset=utf-7"},
    {"Accept":"application/xhtml+xml;charset=utf-7"},
    {"Accept":"text/xml;charset=utf-7"},
    {"Accept":"text/plain;charset=utf-7"},
    {"Accept":"text/javascript"},
    {"Accept":"application/x-javascript"},
    {"Accept":"application/ecmascript"},
    {"Accept":"text/ecmascript"},
    {"Accept":"text/x-json"},
    {"Accept":"text/x-xml"},
    {"Accept":"application/x-json"},
    {"Accept":"text/json"},
    {"Accept":"application/x-www-form-urlencoded"},
    {"Accept":"text/html ,application/json"},
    {"Accept":"text/html , application/json"},
    {"Accept":"text/html;q = 0.9"},
    {"Accept":"text/html ; q=0.9"},
    {"Accept":"text/html;q =0.9"},
    {"Accept":"text/html; q= 0.9"},
    {"Accept":" text/html"},
    {"Accept":"text/html "},
    {"Accept":"  text/html  ,  application/json  "},
    {"Accept":"*/*;q=0.001"},
    {"Accept":"text/html;q=0.001"},
    {"Accept":"application/http-problem"},
    {"Accept":"application/json-problem"},
    {"Accept":"application/xml-problem"},
    {"Accept":"application/vnd.error+json"},
    {"Accept":"application/vnd.error+xml"},
    {"Accept":"text/html,\r\n application/json"},
    {"Accept":"text/html;\r\n q=0.9"},
    {"Accept":"application/server-timing"},
    {"Accept":"application/trace+json"},
    {"Accept":"application/vnd.dtrace"},
    {"Accept":"application/diagnostic+json"},
    {"Accept":"application/davmount+xml"},
    {"Accept":"text/calendar;component=vevent"},
    {"Accept":"text/calendar;component=vtodo"},
    {"Accept":"text/calendar;component=vfreebusy"},
    {"Accept":"text/calendar;method=REQUEST"},
    {"Accept":"text/vcard;version=4.0"},
    {"Accept":"text/vcard;version=3.0"},
    {"Accept":"application/calendar-json"},
    {"Accept":"application/octet-stream"},
    {"Accept":"application/x-raw"},
    {"Accept":"application/binary"},
]