#!/usr/bin/python

"""
This module defines a list of payloads to do http debugging
"""

DEBUG_HEADERS = [
    {"Fastly-Debug": "1" },
    {"Akamai-Debug": "testtoken" },
    {"Akamai-Debug": "1" },
    {"Akamai-EW-Trace": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.test.signature" },
    {"Pragma": "akamai-x-ew-debug" },
    {"Pragma": "akamai-x-ew-debug-rp" },
    {"Pragma": "akamai-x-ew-debug-subs" },
    {"Pragma": "akamai-x-ew-onclientrequest" },
    {"Pragma": "akamai-x-ew-onoriginrequest" },
    {"Pragma": "akamai-x-ew-onoriginresponse" },
    {"Pragma": "akamai-x-ew-onclientresponse" },
    {"Akamai-EW-Debug": "1"},
    {"Akamai-EW-Debug": "true"},
    {"Pragma": "akamai-x-ew-debug-all"},
    {"Akamai-X-Cache-On": "true"},
    {"Akamai-X-Cache-On": "1"},
    {"Akamai-X-Cache-Remote-On": "true"},
    {"Akamai-X-Cache-Remote-On": "1"},
    {"Akamai-X-Check-Cacheable": "YES"},
    {"Akamai-X-Check-Cacheable": "NO"},
    {"Akamai-X-Get-Cache-Key": "1"},
    {"Akamai-X-Get-Cache-Key": "true"},
    {"Akamai-X-Get-True-Cache-Key": "1"},
    {"Akamai-X-Get-True-Cache-Key": "true"},
    {"Akamai-X-Get-Client-IP": "1"},
    {"Akamai-X-Get-Client-IP": "true"},
    {"Akamai-X-Get-Extracted-Values": "1"},
    {"Akamai-X-Get-Extracted-Values": "true"},
    {"Akamai-X-Get-Nonces": "1"},
    {"Akamai-X-Get-Request-ID": "1"},
    {"Akamai-X-Get-Request-ID": "true"},
    {"Akamai-X-Serial-No": "1"},
    {"Akamai-X-Serial-No": "true"},
    {"Akamai-X-Tapioca-Log": "1"},
    {"Akamai-X-Tapioca-Log": "true"},
    {"X-Akamai-Request-ID": "debug-request-123"},
    {"X-Akamai-Request-ID": "1"},
    {"X-Akamai-Staging": "true"},
    {"X-Akamai-Staging": "1"},
    {"Akamai-Staging": "on"},
    {"Akamai-Cache-Control": "no-cache"},
    {"Akamai-Cache-Control": "no-store"},
    {"Akamai-Cache-Control": "max-age=0"},
    {"Akamai-Pragma-Client-IP": "1"},
    {"Akamai-Pragma-Client-IP": "debug"},
    {"Akamai-Origin-Hop": "1"},
    {"Akamai-Origin-Hop": "true"},
    {"X-Akamai-Edge-Connect-Time": "1"},
    {"X-Akamai-Edge-Connect-Time": "debug"},
    {"Akamai-Request-Time": "1"},
    {"Akamai-Request-Start": "1"},
    {"X-Akamai-GEO": "debug"},
    {"X-Akamai-GEO": "1"},
    {"Akamai-GEO": "debug"},
    {"X-Akamai-Edge-Result": "debug"},
    {"X-Akamai-Edge-Result": "1"},
    {"Akamai-Edge-IP": "debug"},
    {"Akamai-Edge-IP": "1"},
    {"Akamai-Request-UUID": "debug-uuid-123"},
    {"Akamai-Request-UUID": "1"},
    {"X-True-Client-IP": "127.0.0.1"},
    {"True-Client-IP": "127.0.0.1"},
    {"Akamai-X-Session-ID": "debug-session-123"},
    {"Akamai-Session-Debug": "1"},
    {"Akamai-Transform-Debug": "1"},
    {"Akamai-Image-Debug": "true"},
    {"Akamai-Forward-Debug": "1"},
    {"X-Akamai-Forward": "debug"},
    {"Akamai-Policy-Debug": "1"},
    {"Akamai-Rule-Debug": "true"},
    {"Akamai-BM-Debug": "1"},
    {"Akamai-Bot-Debug": "true"},
    {"Akamai-WAF-Debug": "1"},
    {"Akamai-Firewall-Debug": "true"},
    {"Akamai-KSD-Debug": "1"},
    {"Akamai-EdgeScape-Debug": "1"},
    {"X-Akamai-EdgeScape": "debug"},
    {"Akamai-mPulse-Debug": "1"},
    {"X-Akamai-mPulse": "debug"},
    {"Akamai-SureRoute-Debug": "1"},
    {"X-Akamai-SureRoute": "debug"},
    {"Akamai-TD-Debug": "1"},
    {"Akamai-Tiered-Debug": "true"},
    {"Akamai-NS-Debug": "1"},
    {"X-Akamai-NetStorage-Debug": "true"},
    {"Akamai-DNS-Debug": "1"},
    {"X-Akamai-FastDNS-Debug": "true"},
    {"Akamai-Ion-Debug": "1"},
    {"X-Akamai-Ion": "debug"},
    {"Akamai-Cloudlet-Debug": "1"},
    {"X-Akamai-Cloudlet": "debug"},
    {"Akamai-ER-Debug": "1"},
    {"Akamai-Redirect-Debug": "true"},
    {"Akamai-VP-Debug": "1"},
    {"Akamai-Priority-Debug": "true"},
    {"Akamai-API-Debug": "1"},
    {"X-Akamai-API-Gateway-Debug": "true"},
    {"Akamai-IM-Debug": "1"},
    {"Akamai-Image-Manager-Debug": "true"},
    {"Akamai-VM-Debug": "1"},
    {"Akamai-Video-Debug": "true"},
    {"Akamai-AMD-Debug": "1"},
    {"X-Akamai-AMD": "debug"},
    {"Akamai-DD-Debug": "1"},
    {"X-Akamai-Download-Debug": "true"},
    {"Akamai-OD-Debug": "1"},
    {"X-Akamai-Object-Debug": "true"},
    {"Pragma": "akamai-x-cache-on"},
    {"Pragma": "akamai-x-cache-remote-on"},
    {"Pragma": "akamai-x-check-cacheable"},
    {"Pragma": "akamai-x-get-cache-key"},
    {"Pragma": "akamai-x-get-true-cache-key"},
    {"Pragma": "akamai-x-get-ssl-client-session-id"},
    {"Pragma": "akamai-x-get-client-ip"},
    {"Pragma": "akamai-x-get-request-id"},
    {"Pragma": "akamai-x-get-extracted-values"},
    {"Pragma": "akamai-x-serial-no"},
    {"Pragma": "akamai-x-get-nonces"},
    {"Pragma": "akamai-x-tapioca-log"},
    {"Akamai-PM-Debug": "1"},
    {"X-Akamai-Property-Debug": "true"},
    {"Akamai-X-Metadata-Debug": "1"},
    {"Akamai-X-Feature-Debug": "1"},
    {"Akamai-X-Behavior-Debug": "1"},
    {"X-Akamai-Diagnostic": "1"},
    {"Akamai-Diagnostic-Mode": "on"},
    {"X-Akamai-Debug-Mode": "verbose"},
    {"Akamai-X-Override-Behavior": "debug"},
    {"X-Akamai-Force-Debug": "1"},
    {"Akamai-Extended-Log": "1"},
    {"X-Akamai-Log-Detail": "full"},
    {"Akamai-Verbose-Log": "true"},
    {"X-Akamai-Test-Mode": "1"},
    {"Akamai-Sandbox": "debug"},
    {"X-Akamai-Config-Version": "debug"},
    {"Akamai-Property-Version": "latest"},
    {"x-envoy-force-trace": "1" },
    {"x-client-trace-id": "b7f1d33a-cb5a-11ee-9b86-0242ac120002" },
    {"x-client-trace-id": "4bf92f3577b34da6a3ce929d0e0e4736" },
    {"X-Dispatcher-Info": "1" },
    {"envoy-debug": "on" },
    {"envoy-debug": "1" },
    {"X-Debug": "1" },
    {"X-Debug": "true" },
    {"X-Debug": "on" },
    {"Debug": "true" },
    {"Debug": "1" },
    {"Debug": "on" },
    {"X-Debug-Mode": "on" },
    {"X-Debug-Mode": "verbose" },
    {"X-Debug-Enabled": "1" },
    {"X-Trace": "true" },
    {"X-Trace": "1" },
    {"X-Trace-Id": "4bf92f3577b34da6a3ce929d0e0e4736" },
    {"X-Trace-Id": "b7f1d33a-cb5a-11ee-9b86-0242ac120002" },
    {"X-Trace-ID": "4bf92f3577b34da6a3ce929d0e0e4736" },
    {"X-Trace-Request": "1" },
    {"X-Trace-Request-Id": "b7f1d33a-cb5a-11ee-9b86-0242ac120002" },
    {"X-Trace-Request-Id": "4bf92f3577b34da6a3ce929d0e0e4736" },
    {"X-Trace-Context": "test-trace-context" },
    {"X-Trace-Context": "{\"trace\":\"test\",\"level\":\"verbose\"}" },
    {"X-Debug-Token": "testtoken" },
    {"X-Debug-Token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.test.signature" },
    {"X-Debug-Token-Link": "https://debug.example.com/token/testtoken" },
    {"X-Debug-Info": "1" },
    {"X-Debug-Trace": "1" },
    {"X-Debug-Request": "1" },
    {"X-Debug-Log": "1" },
    {"X-Debug-Log": "{\"env\":\"dev\",\"level\":\"debug\"}" },
    {"X-Debug-Params": "1" },
    {"X-Debug-Params": "{\"param\":\"value\"}" },
    {"X-Debug-Data": "1" },
    {"X-Debug-Data": "{\"debug\":true}" },
    {"X-Request-ID": "b7f1d33a-cb5a-11ee-9b86-0242ac120002" },
    {"X-Request-ID": "00000000-0000-0000-0000-000000000001" },
    {"X-Request-Id": "b7f1d33a-cb5a-11ee-9b86-0242ac120002" },
    {"X-Correlation-ID": "b7f1d33a-cb5a-11ee-9b86-0242ac120002" },
    {"X-Correlation-ID": "1234567890abcdef1234567890abcdef" },
    {"X-Correlation-Id": "b7f1d33a-cb5a-11ee-9b86-0242ac120002" },
    {"X-B3-TraceId": "4bf92f3577b34da6a3ce929d0e0e4736" },
    {"X-B3-TraceId": "00000000000000000000000000000001" },
    {"X-B3-SpanId": "00f067aa0ba902b7" },
    {"X-B3-ParentSpanId": "b73a1e02db7a4e6d" },
    {"X-B3-Sampled": "1" },
    {"X-B3-Sampled": "0" },
    {"X-B3-Flags": "1" },
    {"traceparent": "00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01" },
    {"tracestate": "vendor=info" },
    {"X-Amzn-Trace-Id": "Root=1-67891233-abcdef012345678912345678;Parent=53995c3f42cd8ad8;Sampled=1" },
    {"X-Cloud-Trace-Context": "105445aa7843bc8bf206b12000100000/1;o=1" },
    {"X-NewRelic-ID": "testtoken" },
    {"X-NewRelic-Transaction": "test-transaction" },
    {"X-Datadog-Trace-Id": "1234567890123456789" },
    {"X-Datadog-Parent-Id": "987654321098765432" },
    {"X-Datadog-Sampling-Priority": "1" },
    {"X-Instana-T": "4bf92f3577b34da6a3ce929d0e0e4736" },
    {"X-Instana-S": "00f067aa0ba902b7" },
    {"X-Instana-L": "1" },
    {"X-AppDynamics-Transaction-Correlation-Header": "testtoken" },
    {"X-Elastic-Traceparent": "00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01" },
    {"X-Honeycomb-Trace": "4bf92f3577b34da6a3ce929d0e0e4736" },
    {"X-OpenTracing-Trace": "test-trace" },
    {"X-OpenTelemetry-TraceId": "4bf92f3577b34da6a3ce929d0e0e4736" },
    {"X-OpenTelemetry-SpanId": "00f067aa0ba902b7" },
    {"X-OpenTelemetry-Sampled": "1" },
    {"X-Env": "debug" },
    {"X-Debug-Request-ID": "b7f1d33a-cb5a-11ee-9b86-0242ac120002" },
    {"X-Debug-Level": "verbose" },
    {"X-Debug-Verbose": "true" },
    {"X-Debug-Trace-Enabled": "true" },
    {"X-Debug-Trace-Id": "4bf92f3577b34da6a3ce929d0e0e4736" },
    {"X-Verbose": "true" },
    {"X-Verbose-Log": "1" },
    {"X-Debug-Stack": "1" },
    {"X-Debug-StackTrace": "{\"stack\":\"test stack trace\"}" },
    {"X-Debug-Source": "true" },
    {"X-Debug-Output": "json" },
    {"X-Debug-Output": "text" },
    {"X-Debug-Print": "true" },
    {"X-Debug-Console": "1" },
    {"X-Debug-Headers": "true" },
    {"X-Debug-Errors": "true" },
    {"X-Debug-Response": "true" },
    {"X-Trace-Enabled": "1" },
    {"X-Trace-Details": "1" },
    {"X-Trace-Logs": "true" },
    {"X-Debug-Trace-Context": "{\"trace\":\"test\"}" },
    {"X-Debug-Trace-Context": "test-trace-context" },
    {"X-Trace-Path": "1" },
    {"X-Trace-Timing": "1" },
    {"X-Trace-Latency": "1" },
    {"X-Trace-Source": "1" },
    {"X-Trace-Depth": "full" },
    {"X-Debug-Perf": "1" },
    {"X-Debug-Profiler": "true" },
    {"X-Debug-Metrics": "true" },
    {"X-Log-Level": "debug" },
    {"X-Log-Level": "trace" },
    {"X-Logging": "debug" },
    {"X-Debug-Logging": "1" },
    {"X-Debug-Logs": "true" },
    {"X-Debug-Timing": "true" },
    {"X-Debug-Trace-Request": "true" },
    {"X-Debug-Trace-Response": "true" },
    {"X-Debug-Mode": "verbose" },
    {"X-Debug-Mode": "on" },
    {"X-Debug-Flag": "1" },
    {"X-Debug-Switch": "on" },
    {"X-Debug-Enabled": "true" },
    {"X-Trace-Mode": "debug" },
    {"X-Debug": "true" },
    {"X-Debug": "on" },
    {"X-Enable-Debug": "true"},
    {"X-Enable-Debug": "1"},
    {"X-Profile": "true"},
    {"X-Profile": "1"},
    {"X-Profiler": "on"},
    {"X-Profiler-Enabled": "true"},
    {"X-Enable-Profiling": "1"},
    {"X-Debug-Profile": "true"},
    {"X-Laravel-Debug": "true"},
    {"X-Laravel-Debug": "1"},
    {"X-Symfony-Debug": "1"},
    {"X-Symfony-Debug": "true"},
    {"X-Symfony-Profiler": "true"},
    {"X-Django-Debug": "true"},
    {"X-Django-Debug": "1"},
    {"X-Rails-Debug": "on"},
    {"X-Rails-Debug": "true"},
    {"X-Spring-Debug": "true"},
    {"X-Spring-Debug": "1"},
    {"X-Flask-Debug": "1"},
    {"X-Flask-Debug": "true"},
    {"X-Express-Debug": "true"},
    {"X-Node-Debug": "true"},
    {"X-Nuxt-Debug": "true"},
    {"X-Next-Debug": "true"},
    {"X-Nextjs-Debug": "true"},
    {"X-Cache-Debug": "true"},
    {"X-Cache-Debug": "1"},
    {"X-Debug-Cache": "on"},
    {"X-Cache-Info": "debug"},
    {"X-Varnish-Debug": "true"},
    {"X-Varnish-Debug": "1"},
    {"X-Varnish-Cache-Debug": "1"},
    {"X-Nginx-Debug": "true"},
    {"X-Redis-Debug": "true"},
    {"X-Debug-Query": "true"},
    {"X-Debug-Query": "1"},
    {"X-Debug-SQL": "1"},
    {"X-Debug-SQL": "true"},
    {"X-Show-Queries": "true"},
    {"X-Show-Queries": "1"},
    {"X-Database-Debug": "on"},
    {"X-Query-Debug": "enabled"},
    {"X-SQL-Debug": "true"},
    {"X-DB-Debug": "1"},
    {"X-Show-Stack": "true"},
    {"X-Show-Stack": "1"},
    {"X-Stack-Trace": "enabled"},
    {"X-Stack-Trace": "true"},
    {"X-Show-Exceptions": "true"},
    {"X-Show-Exceptions": "1"},
    {"X-Exception-Debug": "on"},
    {"X-Show-Errors": "true"},
    {"X-Display-Errors": "1"},
    {"X-Error-Debug": "on"},
    {"X-Error-Reporting": "all"},
    {"X-Environment": "development"},
    {"X-Environment": "dev"},
    {"X-Environment": "debug"},
    {"X-Debug-Env": "development"},
    {"X-App-Env": "development"},
    {"X-App-Debug": "true"},
    {"X-Test-Mode": "true"},
    {"X-Test-Mode": "1"},
    {"X-Test": "1"},
    {"X-Test": "true"},
    {"X-Debug-Test": "on"},
    {"X-Testing": "enabled"},
    {"X-Test-Debug": "true"},
    {"X-Inspect": "true"},
    {"X-Inspect": "1"},
    {"X-Inspector": "on"},
    {"X-Debug-Inspector": "1"},
    {"X-Show-Inspector": "true"},
    {"X-Dev-Mode": "true"},
    {"X-Dev-Mode": "on"},
    {"X-Dev-Mode": "1"},
    {"X-Development": "1"},
    {"X-Developer-Mode": "enabled"},
    {"X-Dev": "true"},
    {"X-Dev": "1"},
    {"X-Cloudflare-Debug": "1"},
    {"X-Cloudflare-Debug": "true"},
    {"CF-Debug": "1"},
    {"CF-Debug": "true"},
    {"Fastly-Trace": "true"},
    {"X-CloudFront-Debug": "true"},
    {"X-Azure-Debug": "true"},
    {"X-Monitor": "debug"},
    {"X-Debug-Monitor": "true"},
    {"X-Monitoring-Debug": "1"},
    {"X-APM-Debug": "enabled"},
    {"X-Route-Debug": "on"},
    {"X-Router-Debug": "enabled"},
    {"X-Session-Debug": "1"},
    {"X-Show-Session": "on"},
    {"X-Template-Debug": "true"},
    {"X-Debug-Template": "1"},
    {"X-View-Debug": "on"},
    {"X-Render-Debug": "enabled"},
    {"X-API-Debug": "true"},
    {"X-API-Debug": "1"},
    {"X-Debug-API": "1"},
    {"X-API-Verbose": "on"},
    {"X-Debug-Auth": "true"},
    {"X-Auth-Debug": "1"},
    {"X-Security-Debug": "on"},
    {"X-Debug-Security": "enabled"},
    {"X-Middleware-Debug": "true"},
    {"X-Debug-Middleware": "1"},
    {"X-Show-Debug-Info": "true"},
    {"X-Debug-Info": "full"},
    {"X-Debug-Mode-Enabled": "yes"},
    {"X-Enable-Debug-Mode": "true"},
    {"X-Debug-All": "1"},
    {"X-Full-Debug": "true"},
    {"X-Deep-Debug": "on"},
    {"X-Super-Debug": "1"},
    {"X-Debug-Performance": "true"},
    {"X-Performance-Debug": "1"},
    {"X-Show-Timing": "1"},
    {"X-Timer": "true"},
    {"X-Debug-Timer": "on"},
    {"Server-Timing": "debug"},
    {"X-Verbose-Mode": "on"},
    {"X-Verbosity": "high"},
    {"X-Verbosity": "debug"},
    {"X-Logging": "enabled"},
    {"X-Debug-Build": "true"},
    {"X-Build-Debug": "1"},
    {"X-Compilation-Debug": "on"},
    {"X-Xdebug": "1"},
    {"X-Xdebug-Session": "PHPSTORM"},
    {"X-Xdebug-Profile": "1"},
    {"XDEBUG_SESSION": "PHPSTORM"},
    {"XDEBUG_PROFILE": "1"},
    {"XDEBUG_TRACE": "1"},
    {"X-Symfony-Trace": "true"},
    {"X-Laravel-Debugbar": "true"},
    {"X-Laravel-Clockwork": "true"},
    {"X-Clockwork-Id": "1234567890"},
    {"X-Django-Debug-Toolbar": "true"},
    {"Djdt-Store-Id": "1234567890"},
    {"X-GraphQL-Debug": "true"},
    {"X-GraphQL-Tracing": "true"},
    {"X-Apollo-Tracing": "1"},
    {"X-WebSocket-Debug": "true"},
    {"X-WS-Debug": "1"},
    {"X-Worker-Debug": "true"},
    {"X-Job-Debug": "1"},
    {"X-Queue-Debug": "true"},
    {"X-Service-Debug": "true"},
    {"X-Microservice-Debug": "1"},
    {"X-Internal-Debug": "true"},
    {"X-Trace-All": "true"},
    {"X-Full-Trace": "1"},
    {"X-Complete-Trace": "true"},
    {"X-Distributed-Trace": "enabled"},
    {"X-Proxy-Debug": "true"},
    {"X-Backend-Debug": "1"},
    {"X-Upstream-Debug": "true"},
    {"X-LB-Debug": "true"},
    {"X-LoadBalancer-Debug": "1"},
    {"X-Lambda-Debug": "true"},
    {"X-Function-Debug": "1"},
    {"X-Serverless-Debug": "true"},
    {"X-Container-Debug": "true"},
    {"X-Docker-Debug": "1"},
    {"X-K8s-Debug": "true"},
    {"X-Kubernetes-Debug": "1"},
    {"X-Zipkin-Trace-Id": "4bf92f3577b34da6a3ce929d0e0e4736"},
    {"X-Zipkin-Span-Id": "00f067aa0ba902b7"},
    {"X-Zipkin-Parent-Span-Id": "b73a1e02db7a4e6d"},
    {"X-Zipkin-Sampled": "1"},
    {"X-Zipkin-Flags": "1"},
    {"Uber-Trace-Id": "4bf92f3577b34da6a3ce929d0e0e4736:00f067aa0ba902b7:0:1"},
    {"Jaeger-Debug-Id": "debug-trace-id"},
    {"Jaeger-Baggage": "key=value"},
    {"X-Lightstep-Trace-Id": "4bf92f3577b34da6a3ce929d0e0e4736"},
    {"X-Lightstep-Span-Id": "00f067aa0ba902b7"},
    {"X-Dynatrace": "FW4;-1316515871;1;1;0;2"},
    {"X-Dynatrace-Tag": "tag-value"},
    {"X-Trace-Options": "trigger-trace"},
    {"X-Trace-Options-Signature": "signature"},
    {"X-Splunk-Trace": "true"},
    {"X-Splunk-Request-Id": "req-id-12345"},
    {"X-Profile-Request": "1"},
    {"X-Blackfire-Query": "enable"},
    {"X-Tideways-Profiler": "1"},
    {"X-PHP-Debug": "1"},
    {"X-Python-Debug": "true"},
    {"X-Node-Inspect": "true"},
    {"X-Ruby-Debug": "1"},
    {"X-Java-Debug": "true"},
    {"X-Go-Debug": "1"},
    {"X-Rust-Debug": "true"},
    {"X-Replay-Request": "true"},
    {"X-Debug-Replay": "1"},
    {"X-Feature-Debug": "true"},
    {"X-Debug-Features": "all"},
    {"X-AB-Test-Debug": "true"},
    {"X-Experiment-Debug": "1"},
    {"X-RateLimit-Debug": "true"},
    {"X-Throttle-Debug": "1"},
    {"X-Auth-Debug-Info": "true"},
    {"X-JWT-Debug": "1"},
    {"X-OAuth-Debug": "true"},
    {"X-Validation-Debug": "true"},
    {"X-Schema-Debug": "1"},
    {"X-Serialization-Debug": "true"},
    {"X-JSON-Debug": "1"},
    {"X-XML-Debug": "true"},
]
