#!/usr/bin/env python3

import argparse  # noqa: F401
import random
import re  # noqa: F401
import os
import socket
import ssl
import string
import sys
import time
import traceback  # noqa: F401
from urllib.parse import (
    urljoin,  # noqa: F401
    urlparse,
)
from collections import defaultdict
import requests
import urllib3
from bs4 import BeautifulSoup
from bs4 import XMLParsedAsHTMLWarning

from modules.logging_config import configure_logger  # noqa: F401
from utils.style import spinner

import requests.utils

import warnings
warnings.filterwarnings("ignore", category=XMLParsedAsHTMLWarning)

def _noop_check_header_validity(header, value=None):
    return None

requests.utils.check_header_validity = _noop_check_header_validity

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

logger = configure_logger(__name__)

CONTENT_DELTA_RANGE = 500
BIG_CONTENT_DELTA_RANGE = 5000


## url tranformation ##
def get_domain_from_url(url: str) -> str:
    domain = urlparse(url).netloc
    return domain


def get_ip_from_url(url: str) -> str:
    domain = get_domain_from_url(url)
    ip = socket.gethostbyname(domain)
    return ip



## Timing requests ##

def human_time(human: str) -> None:
    if human.isdigit():
        time.sleep(int(human))
    elif human.lower() == "r" or human.lower() == "random":
        time.sleep(random.randrange(6))  # nosec B311
    else:
        pass


def verify_waf(url, s, initialResponse, payload=None, wait_count=0):
    random_param = random.randint(0, 99)

    test_url = f"{url}areuawaf{random_param}" if "?" in url else f"{url}?cb=areuawaf{random_param}"
    req = requests.get(test_url, headers={'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0'}, verify=False, timeout=10)

    #print(f"\n=== DEBUG verify_waf ===")
    #print(f"URL: {test_url}")
    #print(f"initialResponse.status_code: {initialResponse.status_code}")
    #print(f"req.status_code: {req.status_code}")
    #print(f"Session headers: {dict(s.headers)}")
    #print(f"Request headers sent: {dict(req.request.headers)}")
    #print(f"========================\n")
    
    html = req.text
    soup = BeautifulSoup(html, "html.parser")
    title = soup.title.string if soup.title else False
    amz_waf = req.headers.get("x-amzn-waf-action", "")
    
    waf_detected = False
    waf_message = ""
    waiting_time = 60
    
    if title and title.lower() == "human verification":
        waf_detected = True
        waf_message = "human verification"
    elif amz_waf and amz_waf.lower() == "captcha":
        waf_detected = True
        waf_message = "Amzn Rate limit"
    elif "verify that you are a real person" in html:
        waf_detected = True
        waf_message = "verify that you are a real person"
    elif "Generated by cloudfront" in html and req.status_code == 403:
        waf_detected = True
        waf_message = "Generated by cloudfront"
    elif initialResponse.status_code not in [405, 403, 412, 429] and req.status_code in [405, 403, 412, 429]:
        waf_detected = True
        waf_message = f"{req.status_code}"
    
    if waf_detected:
        if wait_count == 0:
            print(f" └── [i] [{waf_message}] WAF activated with {payload} payload, wait a moment or try with -hu option")
        spinner(waiting_time, f"        Waiting {waiting_time}s...", wait_count)
        return verify_waf(url, s, initialResponse, payload=payload, wait_count=wait_count+1)
    else:
        return False


## Anti FP ##

def range_exclusion(main_len):
    range_exlusion = (
        range(main_len - CONTENT_DELTA_RANGE, main_len + CONTENT_DELTA_RANGE)
        if main_len < 10000
        else range(
            main_len - BIG_CONTENT_DELTA_RANGE,
            main_len + BIG_CONTENT_DELTA_RANGE,
        )
    )
    return range_exlusion


def fp_baseline(url, s):
    uri = f"{url}{random.randint(1, 99)}"
    headers = {"X-Random-azertyuiop":"azertyuiop"}
    req = s.get(uri, headers=headers, allow_redirects=False, timeout=10)

    fp_base_status = req.status_code
    fp_base_len = len(req.content)
    return fp_base_status, fp_base_len
    

## requests settings ##

def check_auth(auth: str, url: str) -> tuple[str, str] | None:
    try:
        authent = (auth.split(":")[0], auth.split(":")[1])
        r = requests.get(
            url,
            allow_redirects=False,
            verify=False,
            auth=authent,
            timeout=10,  # nosec B501
        )
        if r.status_code in [200, 302, 301]:
            print("\n+ Authentication successful\n")
            return authent
        else:
            print("\nAuthentication error")
            continue_error = input("The authentication seems bad, continue ? [y/N]")
            if continue_error not in ["y", "Y"]:
                print("Exiting")
                sys.exit()
            else:
                return None
    except Exception as e:
        print('Error, the authentication format need to be "user:pass"')
        logger.exception(e)
        sys.exit()


def random_ua():
    with open("./modules/lists/user-agent.lst", "r", encoding="utf-8") as f:
        user_agents = [line.strip() for line in f if line.strip()]

    random_user_agent = {"User-Agent": random.choice(user_agents)}
    return(random_user_agent)


def new_session(base_session=None):
    s = requests.Session()

    if base_session:
        s.verify = base_session.verify
        s.max_redirects = base_session.max_redirects

        s.headers.update(base_session.headers)

        s.proxies.update(base_session.proxies)

        for prefix, adapter in base_session.adapters.items():
            s.mount(prefix, adapter)

    return s

"""def generate_cache_buster(length: int | None = 12) -> str:
    if not isinstance(length, int) or length <= 0:
        raise ValueError("[!] Lenght of cacheBuster be a positive integer")
    return "".join(
        random.choice(string.ascii_lowercase) for i in range(length)  # nosec B311
    )"""